// src/components/FeaturedArticle.tsx
import { Component, Show, createMemo } from "solid-js";
import FeaturedComponentBase from "./FeaturedComponentBase";
import { Article } from "../model";
import { Replace } from "../utils/types";

type FeaturedArticleProps = {
  article: Replace<Article, { elements: Partial<Article["elements"]> }>;
};

const FeaturedArticle: Component<FeaturedArticleProps> = (props) => {
  const shouldRender = createMemo(() => Object.entries(props.article.elements).length > 0);

  return (
    <Show when={shouldRender()}>
      <FeaturedComponentBase type="article" image={props.article.elements?.image}>
        <div>
          <Show when={props.article.elements.title}>
            <h2 class="text-center xl:text-left text-5xl font-semibold text-burgundy">
              {props.article.elements.title!.value}
            </h2>
          </Show>
          <Show when={props.article.elements.publish_date?.value}>
            <p class="text-center xl:text-left text-gray-light mt-6 text-lg">
              {`Published on ${
                new Date(props.article.elements.publish_date!.value!).toLocaleDateString("en-US", {
                  month: "short",
                  year: "numeric",
                  day: "numeric",
                })
              }`}
            </p>
          </Show>
          <Show when={props.article.elements.introduction}>
            <p class="text-left text-gray-700 mt-4 text-xl">
              {props.article.elements.introduction!.value}
            </p>
          </Show>
        </div>
        <a href="#" class="text-center xl:text-left text-burgundy text-xl mt-6 font-semibold underline">
          Read more
        </a>
      </FeaturedComponentBase>
    </Show>
  );
};

export default FeaturedArticle;

// src/components/FeaturedArticle.vue
<template>
  <FeaturedComponentBase
    v-if="shouldRender"
    type="article"
    :image="article.elements?.image"
  >
    <div>
      <h2
        v-if="article.elements.title" 
        class="text-center xl:text-left text-5xl font-semibold text-burgundy"
      >
        {{ article.elements.title.value }}
      </h2>
      <p
        v-if="article.elements.publish_date?.value" 
        class="text-center xl:text-left text-gray-light mt-6 text-lg"
      >
        {{ publishedDateFormatted }}
      </p>
      <p
        v-if="article.elements.introduction" 
        class="text-left text-gray-700 mt-4 text-xl"
      >
        {{ article.elements.introduction.value }}
      </p>
    </div>
    <a
      href="#"
      class="text-center xl:text-left text-burgundy text-xl mt-6 font-semibold underline"
    >
      Read more
    </a>
  </FeaturedComponentBase>
</template>

<script setup lang="ts">
import { computed } from 'vue'
import FeaturedComponentBase from './FeaturedComponentBase.vue'
import type { Article } from '../model'
import type { Replace } from '../utils/types'

type Props = {
  article: Replace<Article, { elements: Partial<Article['elements']> }>
}

const props = defineProps<Props>()

const shouldRender = computed(() => Object.entries(props.article.elements).length > 0)

const publishedDateFormatted = computed(() => {
  if (!props.article.elements.publish_date?.value) return ''
  return `Published on ${new Date(props.article.elements.publish_date.value).toLocaleDateString('en-US', {
    month: 'short',
    year: 'numeric',
    day: 'numeric',
  })}`
})
</script>
